#!/usr/bin/env python3
"""Export everything the C++ plugin takes from the research prototype.

    python scripts/export_plugin_assets.py

Writes (paths relative to the repository root):
    resources/bodies/<name>.wav       body impulse responses, 48 kHz float32 (convolution bodies)
    source/dsp/BodyModes.h            fitted modal banks for the same bodies (light body option)
    tests/golden/bowed_string.json    reference trajectories of the waveguide string for C++ tests

Body sources: CNSM Dataset (Pauget Ballesteros 2026, CC BY 4.0) and the
University of Iowa MIS violin (2012); see research/data/SOURCES.md.
"""

from __future__ import annotations

import json
import math
import shutil
import sys
from pathlib import Path

import numpy as np
import soundfile as sf

RESEARCH = Path(__file__).resolve().parent.parent
REPO = RESEARCH.parent
sys.path.insert(0, str(RESEARCH))

from violin_model.body import BodyModel  # noqa: E402
from violin_model.body_estimation import _smooth_log, compare_responses, fit_modes  # noqa: E402
from violin_model.waveguide import _simulate  # noqa: E402

FS = 48000.0
DIRECT_GAIN = 0.02  # direct path of the modal bank, as used by fit_modes

# Plugin body list: (id used in C++, display name, impulse response in research/data, credit)
BODIES = [
    ("levaggi", "Levaggi", "body_ir_levaggi_48k.wav", "CNSM Dataset (CC BY 4.0)"),
    ("klimke", "Klimke", "body_ir_klimke_48k.wav", "CNSM Dataset (CC BY 4.0)"),
    ("stoppani", "Stoppani", "body_ir_stoppani_48k.wav", "CNSM Dataset (CC BY 4.0)"),
    ("iowa", "Tambovsky (Iowa)", "body_iowa_violin_48k.wav", "University of Iowa MIS"),
]

GOLDEN_CASES = [
    # name, f0, beta, v_bow, f_bow, internal fs, impedance, harmonic tuning
    ("A4_helmholtz", 440.0, 0.10, 0.20, 0.40, 192000.0, 0.197, True),
    ("G3_heavy", 196.0, 0.12, 0.30, 1.40, 192000.0, 0.350, True),
    ("E6_176k", 1318.51, 0.10, 0.20, 0.45, 176400.0, 0.180, True),
    ("A4_multiple_slip", 440.0, 0.10, 0.20, 0.03, 192000.0, 0.197, True),
]
GOLDEN_SAMPLES = 2048
GOLDEN_SECONDS = 0.5


def export_bodies():
    target = REPO / "resources" / "bodies"
    target.mkdir(parents=True, exist_ok=True)
    header_modes = []
    for body_id, name, filename, credit in BODIES:
        ir, fs = sf.read(RESEARCH / "data" / filename)
        assert fs == FS, filename
        shutil.copyfile(RESEARCH / "data" / filename, target / f"{body_id}.wav")

        # Fit a modal bank to the impulse response's magnitude on a log grid.
        spectrum = np.fft.rfft(ir, 1 << 16)
        f = np.fft.rfftfreq(1 << 16, 1 / FS)
        grid = 180.0 * 2 ** (np.arange(0, int(48 * math.log2(10000 / 180)) + 1) / 48)
        target_db = np.interp(grid, f, 20 * np.log10(np.abs(spectrum) + 1e-12))
        # The Iowa estimate is smooth (regularised), so it needs more, gentler resonators.
        smooth = body_id == "iowa"
        modes = fit_modes(grid, target_db, FS, max_modes=80 if smooth else 40,
                          prominence_db=0.3 if smooth else 2.0, direct_gain=DIRECT_GAIN)
        fitted = BodyModel(modes, direct_gain=DIRECT_GAIN)
        w, h = fitted.frequency_response(FS, n=1 << 15)
        fit_db = np.interp(grid, w, 20 * np.log10(np.abs(h) + 1e-12))
        err = compare_responses(grid, _smooth_log(grid, fit_db, 1 / 6), _smooth_log(grid, target_db, 1 / 6))
        print(f"{name}: {len(modes)} modes, fit error {err['rms_db']:.2f} dB RMS (1/6 oct)")
        header_modes.append((body_id, name, credit, modes, fitted.direct_gain))
    write_modes_header(header_modes)


def write_modes_header(bodies):
    lines = [
        "// Generated by research/scripts/export_plugin_assets.py - do not edit.",
        "// Modal banks fitted to the measured body responses (light body option).",
        "// Sources: CNSM Dataset (Pauget Ballesteros 2026, CC BY 4.0), University of Iowa MIS.",
        "#pragma once",
        "",
        "#include <array>",
        "",
        "namespace violinsynth::dsp::bodydata",
        "{",
        "struct Mode",
        "{",
        "    float freq; // Hz",
        "    float q;",
        "    float gain; // linear peak gain of an RBJ constant-0-dB-peak band-pass",
        "};",
        "",
    ]
    for body_id, name, credit, modes, direct in bodies:
        lines.append(f"// {name} - {credit}")
        lines.append(f"inline constexpr float {body_id}DirectGain = {direct:.6f}f;")
        lines.append(f"inline constexpr std::array<Mode, {len(modes)}> {body_id}Modes {{ {{")
        for m in modes:
            lines.append(f"    {{ {m.freq:.1f}f, {m.q:.2f}f, {m.gain:.5f}f }},")
        lines.append("} };")
        lines.append("")
    lines.append("} // namespace violinsynth::dsp::bodydata")
    (REPO / "source" / "dsp" / "BodyModes.h").write_text("\n".join(lines) + "\n")


def export_golden():
    cases = []
    for name, f0, beta, v_bow, f_bow, fs, z, harmonic in GOLDEN_CASES:
        n = int(GOLDEN_SECONDS * fs)
        max_delay = fs / f0 + 8
        buf_size = 1 << int(math.ceil(math.log2(max_delay)))
        force, vel, stick = _simulate(
            np.full(n, f0), np.full(n, beta), np.full(n, v_bow), np.full(n, f_bow), np.zeros(n),
            fs, z, 0.8, 0.3, 0.1, 1.5, 0.25, 4000.0, harmonic, buf_size,
        )
        steady = stick[n // 2 :]
        onsets = np.flatnonzero(steady[:-1] & ~steady[1:])
        cases.append({
            "name": name,
            "f0": f0, "beta": beta, "v_bow": v_bow, "f_bow": f_bow, "internal_fs": fs, "impedance": z,
            "mu_s": 0.8, "mu_d": 0.3, "v0": 0.1, "t60": 1.5, "t60_high": 0.25, "f_high": 4000.0,
            "harmonic_tuning": harmonic,
            "bridge_force": [float(f"{x:.12g}") for x in force[:GOLDEN_SAMPLES]],
            "string_velocity": [float(f"{x:.12g}") for x in vel[:GOLDEN_SAMPLES]],
            "total_samples": n,
            "steady_stick_fraction": float(np.mean(steady)),
            "steady_slips_per_period": float(len(onsets) / (len(steady) / (fs / f0))),
        })
    target = REPO / "tests" / "golden"
    target.mkdir(parents=True, exist_ok=True)
    (target / "bowed_string.json").write_text(json.dumps({
        "description": "Reference output of research/violin_model/waveguide._simulate for the C++ BowedString tests. "
                       "Regenerate with research/scripts/export_plugin_assets.py.",
        "cases": cases,
    }) + "\n")
    print(f"golden: {len(cases)} cases")


if __name__ == "__main__":
    export_bodies()
    export_golden()
