#include "plugin/FactoryPresets.h"

namespace violinsynth::presets
{
namespace
{
// Choice indices (see Parameters.cpp).
constexpr float klimke = 1.0f, stoppani = 2.0f, iowa = 3.0f;
constexpr float monoLegato = 1.0f, poly = 2.0f;
constexpr float bowedGuitar = 1.0f, bowedAcousticGuitar = 2.0f, baroqueViolin = 3.0f;
constexpr float bothPickups = 1.0f, bridgePickup = 2.0f;
constexpr float detache = 1.0f, staccato = 2.0f, spiccato = 3.0f, tremolo = 4.0f, pizzicato = 5.0f, harmonics = 6.0f,
                ponticello = 7.0f, tasto = 8.0f, sordino = 9.0f;
} // namespace

const std::vector<FactoryPreset>& factoryPresets()
{
    // clang-format off
    static const std::vector<FactoryPreset> list {
        // Solo
        { "Default Violin", "Solo",
          "The plugin's default: a balanced solo violin in a small room.",
          {} },
        { "Romantic Soloist", "Solo",
          "Wide, warm vibrato that blooms early, expressive slides and a generous hall.",
          { { "vibratoDepth", 38.0f }, { "vibratoRate", 6.0f }, { "vibratoDelay", 0.18f }, { "portamento", 0.09f },
            { "attack", 0.12f }, { "release", 0.3f }, { "bowPressure", 0.55f }, { "bowPosition", 0.1f },
            { "resonance", 0.4f }, { "humanise", 0.6f }, { "room", 0.32f }, { "width", 0.6f }, { "outputGain", -2.0f } } },
        { "Intimate Close-Mic", "Solo",
          "Close and dry, as if the microphone were a foot from the f-holes.",
          { { "body", klimke }, { "vibratoDepth", 20.0f }, { "attack", 0.06f }, { "room", 0.04f },
            { "width", 0.3f }, { "outputGain", 5.8f } } },
        { "Bright Soloist", "Solo",
          "Bowed nearer the bridge with a firmer grip: a projecting, brilliant tone.",
          { { "body", klimke }, { "bowPosition", 0.075f }, { "bowPressure", 0.65f }, { "vibratoDepth", 30.0f },
            { "vibratoRate", 6.2f }, { "room", 0.2f }, { "outputGain", 3.3f } } },
        { "Dark & Warm", "Solo",
          "Bowed towards the fingerboard on the darker Iowa violin, with a slower vibrato.",
          { { "body", iowa }, { "bowPosition", 0.16f }, { "bowPressure", 0.45f }, { "vibratoDepth", 22.0f },
            { "vibratoRate", 5.2f }, { "room", 0.25f }, { "outputGain", 3.5f } } },
        { "Singing Legato", "Solo",
          "One singing line: every overlapping note slurs, with audible shifts between them.",
          { { "playMode", monoLegato }, { "portamento", 0.12f }, { "attack", 0.15f }, { "release", 0.35f },
            { "vibratoDepth", 32.0f }, { "vibratoDelay", 0.35f }, { "room", 0.3f }, { "outputGain", -1.5f } } },
        { "Concert Soloist", "Solo",
          "A projecting modern soloist on the Stoppani violin: firm bow near the bridge, even vibrato and a mid-size hall.",
          { { "body", stoppani }, { "bowPosition", 0.09f }, { "bowPressure", 0.6f }, { "vibratoDepth", 28.0f },
            { "vibratoRate", 5.8f }, { "vibratoDelay", 0.22f }, { "resonance", 0.35f }, { "room", 0.35f },
            { "width", 0.6f }, { "outputGain", 6.6f } } },
        { "Chamber Violin", "Solo",
          "A string-quartet first violin: modest vibrato, clean strokes and a small, warm room.",
          { { "body", klimke }, { "vibratoDepth", 20.0f }, { "vibratoRate", 5.6f }, { "vibratoDelay", 0.35f },
            { "attack", 0.07f }, { "humanise", 0.55f }, { "room", 0.22f }, { "width", 0.45f }, { "outputGain", 5.9f } } },
        { "Hollywood Solo", "Solo",
          "Slow-blooming, wide vibrato, long swells and slides, in a big wide hall for film cues.",
          { { "vibratoDepth", 34.0f }, { "vibratoRate", 6.0f }, { "vibratoDelay", 0.25f }, { "attack", 0.18f },
            { "release", 0.45f }, { "portamento", 0.07f }, { "room", 0.6f }, { "width", 0.85f } } },
        { "Jazz Violin", "Solo",
          "Quick attacks, a late fast vibrato and small scoops, dry like a club stage.",
          { { "body", klimke }, { "attack", 0.04f }, { "vibratoDepth", 26.0f }, { "vibratoRate", 6.3f },
            { "vibratoDelay", 0.4f }, { "portamento", 0.06f }, { "humanise", 0.65f }, { "room", 0.15f },
            { "width", 0.4f }, { "outputGain", 5.8f } } },
        { "Fiery Virtuoso", "Solo",
          "Fast, brilliant separate bows near the bridge with a quick, tight vibrato.",
          { { "articulation", detache }, { "body", klimke }, { "attack", 0.02f }, { "release", 0.06f },
            { "bowPosition", 0.08f }, { "bowPressure", 0.65f }, { "vibratoDepth", 22.0f }, { "vibratoRate", 6.8f },
            { "vibratoDelay", 0.1f }, { "room", 0.25f }, { "width", 0.5f },
            { "outputGain", 4.4f } } },

        // Styles
        { "Baroque", "Styles",
          "Almost no vibrato, a lighter bow and ringing open strings, in a resonant church.",
          { { "body", iowa }, { "vibratoDepth", 6.0f }, { "vibratoDelay", 0.6f }, { "vibratoRate", 5.0f },
            { "attack", 0.1f }, { "bowPosition", 0.13f }, { "bowPressure", 0.45f }, { "humanise", 0.3f },
            { "resonance", 0.55f }, { "portamento", 0.02f }, { "room", 0.35f }, { "outputGain", 2.5f } } },
        { "Folk Fiddle", "Styles",
          "Quick, gritty bowing, little vibrato and droning open strings.",
          { { "body", klimke }, { "attack", 0.03f }, { "release", 0.08f }, { "bowPosition", 0.09f },
            { "bowPressure", 0.62f }, { "vibratoDepth", 10.0f }, { "vibratoDelay", 0.5f }, { "vibratoRate", 6.0f },
            { "portamento", 0.03f }, { "resonance", 0.6f }, { "room", 0.1f }, { "outputGain", 4.4f } } },
        { "Gypsy Swing", "Styles",
          "A fast, wide vibrato from the first moment and slides between notes.",
          { { "vibratoDepth", 45.0f }, { "vibratoRate", 6.8f }, { "vibratoDelay", 0.12f }, { "portamento", 0.1f },
            { "attack", 0.05f }, { "bowPosition", 0.09f }, { "bowPressure", 0.6f }, { "room", 0.2f }, { "outputGain", -2.0f } } },
        { "Fiddle Double Stops", "Styles",
          "Every note gets its own string: play chords and drones with a sharp attack.",
          { { "playMode", poly }, { "resonance", 0.7f }, { "attack", 0.04f }, { "vibratoDepth", 12.0f },
            { "bowPressure", 0.6f }, { "room", 0.12f }, { "outputGain", -1.3f } } },
        { "Film Lyrical", "Styles",
          "Slow, swelling attacks in a large, wide hall for sustained cinematic lines.",
          { { "vibratoDepth", 30.0f }, { "vibratoRate", 5.4f }, { "vibratoDelay", 0.4f }, { "attack", 0.25f },
            { "release", 0.6f }, { "portamento", 0.08f }, { "room", 0.55f }, { "width", 0.8f },
            { "humanise", 0.6f }, { "outputGain", -2.0f } } },
        { "Baroque Violin", "Styles",
          "Gut strings, a light, grainy bow that lets each note ring on, sparing vibrato and freer intonation, as in historically informed playing.",
          { { "instrument", baroqueViolin }, { "bowNoise", 1.0f }, { "bowPressure", 0.7f },
            { "vibratoDepth", 12.0f }, { "vibratoRate", 5.4f }, { "intonation", 0.31f }, { "room", 0.35f } } },
        { "Klezmer Cry", "Styles",
          "An immediate, wide, sobbing vibrato and long slides between notes.",
          { { "vibratoDepth", 42.0f }, { "vibratoRate", 6.6f }, { "vibratoDelay", 0.05f }, { "portamento", 0.14f },
            { "humanise", 0.7f }, { "bowPressure", 0.58f }, { "room", 0.25f }, { "width", 0.5f } } },
        { "Irish Reel", "Styles",
          "Snappy separate bows, almost no vibrato and a bit of drone, close and dry for dance tunes.",
          { { "articulation", detache }, { "attack", 0.02f }, { "release", 0.05f }, { "vibratoDepth", 6.0f },
            { "vibratoRate", 6.5f }, { "vibratoDelay", 0.6f }, { "bowPressure", 0.62f }, { "bowPosition", 0.085f },
            { "resonance", 0.5f }, { "room", 0.12f }, { "width", 0.4f } } },
        { "Bluegrass Drone", "Styles",
          "Every note on its own string so double stops and drones ring together, with a gritty bow.",
          { { "playMode", poly }, { "resonance", 0.8f }, { "bowPressure", 0.62f }, { "bowNoise", 0.7f },
            { "vibratoDepth", 8.0f }, { "attack", 0.04f }, { "room", 0.1f }, { "width", 0.45f } } },
        { "Tango Bite", "Styles",
          "Short, heavy martele strokes with a little grit, for accented tango lines.",
          { { "articulation", staccato }, { "bowPressure", 0.72f }, { "bowPosition", 0.085f },
            { "imperfection", 0.15f }, { "vibratoDepth", 20.0f }, { "vibratoRate", 6.0f }, { "room", 0.18f },
            { "width", 0.45f } } },

        // Articulations
        { "Detache", "Articulations",
          "A new bow stroke for every note, even when notes overlap.",
          { { "articulation", detache }, { "room", 0.2f }, { "outputGain", 0.0f } } },
        { "Staccato", "Articulations",
          "Short, bitten martele strokes. The bow stops on the string.",
          { { "articulation", staccato }, { "room", 0.25f }, { "outputGain", 3.5f } } },
        { "Spiccato", "Articulations",
          "Light bouncing strokes for fast passages.",
          { { "articulation", spiccato }, { "room", 0.25f }, { "outputGain", 7.3f } } },
        { "Tremolo", "Articulations",
          "Rapid bow reversals on every note.",
          { { "articulation", tremolo }, { "vibratoDepth", 15.0f }, { "room", 0.35f }, { "outputGain", 4.5f } } },
        { "Pizzicato", "Articulations",
          "Plucked strings with open-string resonance.",
          { { "articulation", pizzicato }, { "resonance", 0.5f }, { "vibratoDepth", 10.0f }, { "room", 0.25f }, { "outputGain", 5.0f } } },
        { "Pizzicato Hall", "Articulations",
          "Plucked strings in a big hall.",
          { { "articulation", pizzicato }, { "body", stoppani }, { "resonance", 0.5f }, { "vibratoDepth", 10.0f },
            { "room", 0.6f }, { "width", 0.8f }, { "outputGain", 12.0f } } },
        { "Harmonics", "Articulations",
          "Pure, flute-like natural harmonics.",
          { { "articulation", harmonics }, { "vibratoDepth", 12.0f }, { "room", 0.45f }, { "outputGain", 3.0f } } },
        { "Sul Ponticello", "Articulations",
          "Bowed right by the bridge: glassy and ghostly.",
          { { "articulation", ponticello }, { "vibratoDepth", 8.0f }, { "room", 0.3f }, { "outputGain", -2.0f } } },
        { "Sul Tasto", "Articulations",
          "Bowed over the fingerboard: soft and veiled (flautando).",
          { { "articulation", tasto }, { "vibratoDepth", 18.0f }, { "room", 0.35f }, { "outputGain", 3.5f } } },
        { "Con Sordino", "Articulations",
          "With a mute on the bridge: hushed and intimate.",
          { { "articulation", sordino }, { "vibratoDepth", 24.0f }, { "room", 0.3f }, { "outputGain", 3.5f } } },
        { "Velvet Sul Tasto", "Articulations",
          "Bowed over the fingerboard: flute-like, breathy and dark, in a soft hall.",
          { { "articulation", tasto }, { "vibratoDepth", 14.0f }, { "attack", 0.2f }, { "release", 0.4f },
            { "room", 0.4f }, { "width", 0.6f }, { "outputGain", 2.6f } } },
        { "Glass Ponticello", "Articulations",
          "Right at the bridge with slow swells: a cold, glassy shimmer for suspense.",
          { { "articulation", ponticello }, { "playMode", poly }, { "attack", 0.35f }, { "release", 0.7f },
            { "vibratoDepth", 6.0f }, { "room", 0.6f }, { "width", 0.9f }, { "outputGain", -3.0f } } },
        { "Ghost Tremolo", "Articulations",
          "Muted tremolo far back in a large space: a nervous whisper.",
          { { "articulation", tremolo }, { "sordino", 0.7f }, { "room", 0.75f }, { "width", 1.0f },
            { "vibratoDepth", 0.0f }, { "outputGain", 4.9f } } },
        { "Whisper Harmonics", "Articulations",
          "Pure flageolet tones floating in a wide, long hall.",
          { { "articulation", harmonics }, { "release", 0.8f }, { "room", 0.7f }, { "width", 0.9f } } },
        { "Marcato Epic", "Articulations",
          "Heavy, bitten strokes near the bridge in a big hall for trailer-style hits.",
          { { "articulation", staccato }, { "bowPressure", 0.78f }, { "bowPosition", 0.08f },
            { "vibratoDepth", 24.0f }, { "room", 0.5f }, { "width", 0.8f }, { "outputGain", 3.7f } } },
        { "Studio Spiccato", "Articulations",
          "Light bouncing strokes, close and dry, for fast pop and game runs.",
          { { "articulation", spiccato }, { "room", 0.08f }, { "width", 0.3f }, { "humanise", 0.4f }, { "outputGain", 7.2f } } },
        { "Pizzicato Harp", "Articulations",
          "Plucked notes with ringing sympathetic strings in a wide hall, like a small harp.",
          { { "articulation", pizzicato }, { "resonance", 0.65f }, { "room", 0.7f }, { "width", 0.9f }, { "outputGain", 4.4f } } },
        { "Dry Pizzicato Groove", "Articulations",
          "Close, dry plucks with a short ring, for rhythmic parts.",
          { { "articulation", pizzicato }, { "resonance", 0.15f }, { "room", 0.04f }, { "width", 0.3f },
            { "humanise", 0.6f }, { "outputGain", 4.7f } } },

        // Character
        { "Practice Mute", "Character",
          "A heavy practice mute in a small, dry room.",
          { { "sordino", 1.0f }, { "vibratoDepth", 20.0f }, { "room", 0.02f }, { "width", 0.2f }, { "outputGain", 3.3f } } },
        { "Eerie Tremolo", "Character",
          "A light tremolo near the bridge in a vast space: horror-film tension.",
          { { "articulation", tremolo }, { "bowPosition", 0.065f }, { "bowPressure", 0.25f }, { "vibratoDepth", 0.0f },
            { "room", 0.65f }, { "width", 0.9f }, { "outputGain", 2.0f } } },
        { "Dry Studio", "Character",
          "No room at all and a narrow image: add your own reverb in the mix.",
          { { "room", 0.0f }, { "width", 0.25f } } },
        { "Slow Swells", "Character",
          "Long swelling attacks and releases for pads and textures.",
          { { "attack", 0.45f }, { "release", 0.8f }, { "vibratoDelay", 0.6f }, { "bowPressure", 0.45f },
            { "room", 0.45f }, { "width", 0.7f }, { "outputGain", -0.8f } } },
        { "Student Violin", "Character",
          "A keen third-year student: wobbly vibrato, audible slides and the odd rough stroke.",
          { { "imperfection", 0.3f }, { "humanise", 0.95f }, { "vibratoDepth", 16.0f }, { "vibratoRate", 6.9f },
            { "vibratoDelay", 0.15f }, { "portamento", 0.1f }, { "room", 0.12f }, { "width", 0.35f } } },
        { "Muted Chamber", "Character",
          "A half-muted violin in a small room: veiled and gentle, for background lines.",
          { { "sordino", 0.6f }, { "vibratoDepth", 16.0f }, { "vibratoRate", 5.4f }, { "attack", 0.12f },
            { "room", 0.3f }, { "width", 0.5f }, { "outputGain", 2.2f } } },
        { "Ambient Bloom", "Character",
          "Very slow swells that overlap into chords, in a huge, wide space.",
          { { "playMode", poly }, { "attack", 0.5f }, { "release", 1.0f }, { "vibratoDepth", 12.0f },
            { "vibratoRate", 4.2f }, { "vibratoDelay", 0.8f }, { "bowPressure", 0.4f }, { "room", 0.8f },
            { "width", 1.0f } } },

        // Expressive
        { "MPE Expressive", "Expressive",
          "For MPE controllers: per-note bend, pressure adds vibrato and slide moves the bow.",
          { { "mpe", 1.0f }, { "vibratoDepth", 15.0f }, { "vibratoDelay", 0.2f }, { "humanise", 0.4f },
            { "room", 0.25f } } },
        { "Mono Lead", "Expressive",
          "A monophonic lead line with quick, natural shifts: ideal for a keyboard melody.",
          { { "playMode", monoLegato }, { "portamento", 0.07f }, { "attack", 0.07f }, { "vibratoDepth", 28.0f },
            { "room", 0.25f }, { "outputGain", -0.5f } } },

        // Bowed Guitar (docs/BOWED_GUITAR.md)
        { "Bowed Guitar", "Bowed Guitar",
          "An electric guitar played with a violin bow: neck pickup, a warm amp, the neighbouring strings humming along.",
          { { "instrument", bowedGuitar }, { "attack", 0.15f }, { "release", 0.4f }, { "vibratoDepth", 18.0f },
            { "vibratoDelay", 0.4f }, { "room", 0.3f }, { "width", 0.6f }, { "outputGain", 5.1f } } },
        { "Heavy Bowed Guitar", "Bowed Guitar",
          "The late-sixties sound: bridge pickup into a cranked amp, slow swells and a big room.",
          { { "instrument", bowedGuitar }, { "pickup", bridgePickup }, { "drive", 0.8f }, { "drone", 0.7f },
            { "attack", 0.25f }, { "release", 0.6f }, { "vibratoDepth", 22.0f }, { "vibratoDelay", 0.3f },
            { "room", 0.5f }, { "width", 0.75f }, { "outputGain", 4.8f } } },
        { "Bowed Drone Wash", "Bowed Guitar",
          "Every note bows the strings around it: slow chords become a shimmering wall.",
          { { "instrument", bowedGuitar }, { "pickup", bothPickups }, { "drive", 0.5f }, { "drone", 1.0f },
            { "playMode", poly }, { "attack", 0.45f }, { "release", 1.0f }, { "vibratoDepth", 8.0f },
            { "room", 0.65f }, { "width", 0.9f }, { "outputGain", 9.2f } } },
        { "Bowed Acoustic", "Bowed Guitar",
          "A steel-string acoustic played with a violin bow: woody and breathy, the open strings humming along.",
          { { "instrument", bowedAcousticGuitar }, { "drone", 0.3f }, { "attack", 0.2f }, { "release", 0.5f },
            { "vibratoDepth", 15.0f }, { "vibratoDelay", 0.35f }, { "room", 0.35f }, { "width", 0.6f }, { "outputGain", 5.6f } } },
        { "Cinematic Bowed Acoustic", "Bowed Guitar",
          "Dark, slow swells on a bowed acoustic in a big hall, in the style of modern fantasy TV scores.",
          { { "instrument", bowedAcousticGuitar }, { "drone", 0.6f }, { "bowPosition", 0.14f }, { "attack", 0.45f },
            { "release", 1.0f }, { "vibratoDepth", 20.0f }, { "vibratoDelay", 0.5f }, { "room", 0.6f },
            { "width", 0.8f }, { "outputGain", 6.8f } } },
        { "Lo-fi Bowed Guitar", "Bowed Guitar",
          "The electric bowed guitar through the bridge pickup with the amp pushed hard.",
          { { "instrument", bowedGuitar }, { "pickup", bridgePickup }, { "drive", 0.75f }, { "drone", 0.2f },
            { "vibratoDepth", 14.0f }, { "room", 0.2f }, { "width", 0.5f }, { "outputGain", 7.1f } } },
        { "Campfire Bowed Acoustic", "Bowed Guitar",
          "The bowed acoustic guitar, close and dry, with its strings left to ring.",
          { { "instrument", bowedAcousticGuitar }, { "resonance", 0.6f }, { "vibratoDepth", 10.0f },
            { "attack", 0.1f }, { "room", 0.15f }, { "width", 0.5f },
            { "outputGain", 5.8f } } },
    };
    // clang-format on
    return list;
}
} // namespace violinsynth::presets
