"""Violin body as a parallel bank of resonant modes.

Each mode is a two-pole band-pass resonator (RBJ "constant 0 dB peak gain"),
so a mode's `gain` is its peak gain relative to the others. The bank is driven
by the bridge force and its sum approximates the radiated sound.

The default table in data/body_modes.json has two parts:

* Named low modes (A0, CBR, B1-, B1+ and so on) with frequencies, Q values and
  levels chosen within the ranges reported for good violins (Jansson;
  Bissinger 2008; Woodhouse 2014).
* A deterministic set of denser higher modes, generated with a fixed seed.
  Their spacing increases with frequency, and their levels follow a smooth
  envelope with a broad "bridge hill" around 2.5 kHz.

These are plausible starting values, not a measurement of a particular
instrument. Replacing them with a measured bridge admittance or radiativity is
a Phase 3 task.
"""

from __future__ import annotations

import json
import math
from dataclasses import asdict, dataclass
from pathlib import Path

import numpy as np
from scipy.signal import freqz, lfilter

DEFAULT_MODES_PATH = Path(__file__).resolve().parent.parent / "data" / "body_modes.json"


@dataclass(frozen=True)
class Mode:
    freq: float  # Hz
    q: float
    gain: float  # linear peak gain
    name: str = ""


NAMED_LOW_MODES = [
    Mode(275.0, 18.0, 0.90, "A0 (Helmholtz air)"),
    Mode(405.0, 30.0, 0.25, "CBR"),
    Mode(460.0, 28.0, 1.00, "B1-"),
    Mode(480.0, 25.0, 0.35, "A1 (air)"),
    Mode(540.0, 30.0, 0.95, "B1+"),
    Mode(650.0, 30.0, 0.40, ""),
    Mode(760.0, 30.0, 0.45, ""),
]


def _bridge_hill_envelope(freq: np.ndarray) -> np.ndarray:
    """Smooth level envelope: gentle roll-off plus a broad peak near 2.5 kHz."""
    base = 0.55 / (1.0 + (freq / 4000.0) ** 2)
    hill = 0.45 * np.exp(-0.5 * (np.log2(freq / 2500.0) / 0.35) ** 2)
    return base + hill


def generate_default_modes(seed: int = 1715, f_min: float = 850.0, f_max: float = 8000.0) -> list[Mode]:
    """Named low modes plus a seeded set of higher modes."""
    rng = np.random.default_rng(seed)
    modes = list(NAMED_LOW_MODES)
    f = f_min
    while f < f_max:
        spacing = 60.0 + 0.06 * f  # modal overlap grows with frequency
        f_mode = f * (1.0 + 0.02 * rng.standard_normal())
        level = float(_bridge_hill_envelope(np.array([f_mode]))[0]) * (0.6 + 0.4 * rng.random())
        q = float(np.clip(35.0 - 0.003 * f_mode + 4.0 * rng.standard_normal(), 12.0, 45.0))
        modes.append(Mode(round(f_mode, 1), round(q, 1), round(level, 3)))
        f += spacing
    return modes


def save_modes(modes: list[Mode], path: Path = DEFAULT_MODES_PATH) -> None:
    payload = {
        "description": (
            "Violin body modal bank for the Phase 1 prototype. Low modes are named "
            "and set within published ranges; higher modes are generated by "
            "violin_model.body.generate_default_modes(seed=1715). Gains are linear "
            "peak gains of RBJ constant-0dB-peak band-pass resonators, driven by bridge force."
        ),
        "modes": [asdict(m) for m in modes],
    }
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(payload, indent=2) + "\n")


def load_modes(path: Path = DEFAULT_MODES_PATH) -> list[Mode]:
    data = json.loads(Path(path).read_text())
    return [Mode(**m) for m in data["modes"]]


def resonator_coefficients(freq: float, q: float, fs: float):
    """RBJ band-pass (constant 0 dB peak gain) biquad coefficients (b, a)."""
    w0 = 2.0 * math.pi * freq / fs
    alpha = math.sin(w0) / (2.0 * q)
    b = np.array([alpha, 0.0, -alpha])
    a = np.array([1.0 + alpha, -2.0 * math.cos(w0), 1.0 - alpha])
    return b / a[0], a / a[0]


class BodyModel:
    def __init__(self, modes: list[Mode] | None = None, direct_gain: float = 0.05):
        self.modes = modes if modes is not None else load_modes()
        self.direct_gain = direct_gain

    def active_modes(self, fs: float) -> list[Mode]:
        return [m for m in self.modes if m.freq < 0.45 * fs]

    def process(self, x: np.ndarray, fs: float) -> np.ndarray:
        y = self.direct_gain * x
        for m in self.active_modes(fs):
            b, a = resonator_coefficients(m.freq, m.q, fs)
            y = y + m.gain * lfilter(b, a, x)
        return y

    def frequency_response(self, fs: float, n: int = 16384):
        """Complex response of the whole bank on n frequencies up to fs/2."""
        w, h = freqz([self.direct_gain], [1.0], worN=n, fs=fs)
        for m in self.active_modes(fs):
            b, a = resonator_coefficients(m.freq, m.q, fs)
            _, hm = freqz(b, a, worN=n, fs=fs)
            h = h + m.gain * hm
        return w, h
